# Generated by Django 6.0.4 on 2026-04-24 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arena',
            fields=[
                ('arena_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('min_battles_won', models.IntegerField()),
                ('max_battles_won', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], max_length=10)),
                ('elixircost', models.IntegerField()),
                ('type', models.CharField(choices=[('troop', 'Troop'), ('spell', 'Spell'), ('building', 'Building')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('clan_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('battles_won', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('arena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.arena')),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.clan')),
            ],
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('battle_id', models.IntegerField(primary_key=True, serialize=False)),
                ('played_at', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='game.player')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='game.player')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='game.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayersCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.card')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player')),
            ],
            options={
                'unique_together': {('player', 'card')},
            },
        ),
    ]
